### ISSUE TITLE
javascript error while opening 

### ISSUE THREAD

**Issue by keyvann** [terkelg/ramme#70] opened 2016-10-09 19:22 UTC
![image](https://cloud.githubusercontent.com/assets/22478304/19223053/fb48087a-8e72-11e6-89a9-8e497c6307cd.png)

**Comment by terkelg** [comment] 2016-10-10 19:02
Thanks for reporting this. This is a known issue, and I'll do a rewrite soon and fix this issue.
Duplicate of #55.

**Closed by terkelg** 2016-10-10 19:02 UTC
