### ISSUE TITLE
Pull to refresh

### ISSUE THREAD

**Issue by brandonmcconnell** [terkelg/ramme#63] opened 2016-09-26 17:56 UTC
Currently, I see no way to update/refresh feeds or posts. So if I am checking the number of likes on my own photo, I have to completely quit the app and reopen it. Implementing a pull to refresh would be great.

**Comment by terkelg** [comment] 2016-09-26 20:14
Duplicate of #10 #7

**Closed** 2016-10-05 14:16 UTC
