### ISSUE TITLE
Missing GUI components, some keyboard shortcuts don't work, options screen formatting incorrect, window resize does not work

### ISSUE THREAD

**Issue by laczik** [terkelg/ramme#183] opened 2017-08-16 08:59 UTC
Issues as described in the title; also see screenshots:
[http://cloud.laczik.org/index.php/s/FUTQJpi36EIqHbd](http://cloud.laczik.org/index.php/s/FUTQJpi36EIqHbd)
[http://cloud.laczik.org/index.php/s/KCZhf6sGtOLbiAa](http://cloud.laczik.org/index.php/s/KCZhf6sGtOLbiAa)

It would be helpful if there were build instructions, especially for those who don't normally use java/javascript so that one could also try the latest version.
            -

            Ramme 3.2.3 (installed from deb package)
            Electron 1.7.2
            linux x64 4.10.0-30-generic

**Comment by bil-elmoussaoui** [comment] 2017-08-17 10:22
Duplicate of https://github.com/terkelg/ramme/issues/176

**Closed by bil-elmoussaoui** 2017-08-17 10:22 UTC

**Comment by laczik** [comment] 2017-08-17 10:34
Hi,

I would be happy to take a look and try to fix, but since I do not normally do JavaScript development, instructions - however brief - on how to compile the code would be helpful to get me started.
(I know JavaScript, but not the development environment used for ramme... mvn/gradle/gulp or what is it?)

Thanks,

John

**Comment by bil-elmoussaoui** [comment] 2017-08-17 10:38
@laczik mvn & gardle are Java(Android dev tools). Gulp is just an automatization tool for Javascript dev. We use Electron + SASS (for CSS) + some basic JS (NodeJS ofc)
I will add some building steps to the README whenever I can but normally you should just clone the repository and run `npm build && npm start` you will need `nodejs` `npm` that you can find in your package manager (whatever Linux distro you're using).

**Comment by laczik** [comment] 2017-08-17 10:44
Hi Bilal,

OK, thanks - that's all I needed... I will take a look when I get some free time. If I get around to it before you, I will also try to update the README with the building steps.

How was the deb package generated? Is there a deb source package?

Thanks,

John

**Comment by bil-elmoussaoui** [comment] 2017-08-17 10:48
The deb package is generated using electron-builder & travis. See here for travis 
https://github.com/terkelg/ramme/blob/7d2a5bbe335d60bd39f134c274ba990d6a0e0959/.travis.yml#L26-L27
and here for electron builder
https://github.com/terkelg/ramme/blob/7d2a5bbe335d60bd39f134c274ba990d6a0e0959/package.json#L8
https://github.com/terkelg/ramme/blob/7d2a5bbe335d60bd39f134c274ba990d6a0e0959/gulpfile.babel.js#L65
