### ISSUE TITLE
Error on version 3.0.1 on Ubuntu Gnome 16.04 Linux

### ISSUE THREAD

**Issue by j-keiter** [terkelg/ramme#83] opened 2017-01-16 21:16 UTC
![2017-01-16_rammeerror](https://cloud.githubusercontent.com/assets/24608664/21999230/db8ea228-dbed-11e6-8505-5606d95f6f31.png)

**Comment by anatolinicolae** [comment] 2017-01-16 21:18
Dupe of #82.

**Closed by anatolinicolae** 2017-01-16 21:18 UTC
Labels: duplicate
