### ISSUE TITLE
white blank space between feed and sidebar on ubuntu

### ISSUE THREAD

**Issue by v77v** [terkelg/ramme#143] opened 2017-06-01 08:42 UTC
on discovery, the main feed and even the login screen there's a big white space on the left hand side.

i uploaded to imgur a image of it:
![issue](http://i.imgur.com/kx5tpnkl.png)

i'm using xfce on ubuntu 16.04

**Comment by VoOoLoX** [comment] 2017-06-01 08:55
Duplicate of #125

**Closed** 2017-06-01 11:51 UTC
