### ISSUE TITLE
Instagram Direct Support

### ISSUE THREAD

**Issue by bhberson** [terkelg/ramme#53] opened 2016-09-17 16:01 UTC
Would be nice to have IG Direct support to message folks. I know this is mostly a wrapper of the web UI which doesn't have this, but also on the roadmap is "Stories" which is not supported by the web...

**Comment by terkelg** [comment] 2016-09-23 21:44
Thanks for the feature request. This is a duplicate of #1, and I might add this in future releases.

**Closed by terkelg** 2016-09-23 21:44 UTC
