### ISSUE TITLE
Looks bad on ubuntu 17.04 

### ISSUE THREAD

**Issue by ed4jonson** [terkelg/ramme#134] opened 2017-05-30 03:44 UTC
This is how app looks like on ubuntu 17.04
https://www.dropbox.com/s/1kptfi4y7igh9g7/Screenshot%20from%202017-05-30%2006-43-30.png?dl=0
            -

            Ramme 3.2.2
            Electron 1.7.2
            linux x64 4.10.0-21-generic

**Comment by ThomasDavidDev** [comment] 2017-05-30 08:23
That's a bit of short description I think.

But i can confirm there are also a few bugs in Ubuntu 16.04. I can only re-size the screen when I close it and then reopen with the toggle button in the status bar. There's also something wrong with the padding when the apps open's in normal resolution.

Thomas

**Comment by survivor303** [comment] 2017-05-30 14:37
yep, pictures are little bit too much on right edge and it not respect black/dark theme mode on gnome. but the app itself is great :)

**Comment by davidcortesortuno** [comment] 2017-05-30 15:18
It also looks bad as the picture above, in Arch Linux with the `.pacman` package in the `3.2.2` version

**Comment by alexsalex** [comment] 2017-05-30 17:37
MacOS 10.12.5 same things... looks ugly...

**Comment by bil-elmoussaoui** [comment] 2017-05-30 21:20
Duplicate of #125

**Closed by bil-elmoussaoui** 2017-05-30 21:20 UTC
