### ISSUE TITLE
UI Alignment Borked on Windows

### ISSUE THREAD

**Issue by EposVox** [terkelg/ramme#133] opened 2017-05-29 15:44 UTC
![8488460b9cd348aea14055e840889341 1](https://cloud.githubusercontent.com/assets/18689681/26555640/13f24154-4464-11e7-8222-e5fbb8ec5f97.png)

UHD & 1440p Monitor w/ 125% scaling. Feed and Home button get cut off by Instagram logo bar, and images cut off on the right.
I also have a 1080p monitor w/ 100% scaling, but moving the Ramme window to that monitor and resizing does not fix.

Windows 10 64-bit. Anniversary Update.

**Comment by bil-elmoussaoui** [comment] 2017-05-29 15:47
Duplicate of #125

**Closed** 2017-05-30 21:21 UTC
Labels: duplicate
