### ISSUE TITLE
Sidebar overlaps body content

### ISSUE THREAD

**Issue by d0od88** [terkelg/ramme#114] opened 2017-05-14 18:10 UTC
In the default vertical layout the sidebar overlaps with the main content in all available views, including home, discover, profile and notifications.

![screenshot from 2017-05-14 19-09-48](https://cloud.githubusercontent.com/assets/869982/26036639/0bb9fd74-38d9-11e7-97fb-4f3c97ba8100.png)

            Ramme 3.1.0
            Electron 1.7.0
            linux x64 4.10.0-21-generic

**Comment by terkelg** [comment] 2017-05-14 18:58
Strange, I don't have that issue. Can you try to inspect it in the dev build and give me the selector?

**Comment by anatolinicolae** [comment] 2017-05-14 18:59
I'll have a look into this since I saw it it some pages, not all. Will check and push a fix ASAP.

**Comment by yimankaing** [comment] 2017-05-21 14:59
I get this too on linux

**Comment by PetersenLars** [comment] 2017-05-23 09:11
I have the same issue on MacOS. 

Ramme 3.1.0.80
MacOS 10.12.4

**Comment by alexslee** [comment] 2017-05-23 21:19
Same issue, v3.1.0.80 on 10.12.4. Happens right after logging in without any other adjustments, and occurs on every page of Insta for me
<img width="484" alt="screen shot 2017-05-23 at 2 17 34 pm" src="https://cloud.githubusercontent.com/assets/18637446/26376800/a9141d3a-3fc2-11e7-8b6b-fc5410803177.png">

**Comment by brandonb927** [comment] 2017-05-24 05:56
Just installed Ramme again and am seeing this issue: 
![image](https://cloud.githubusercontent.com/assets/1509352/26388725/e49b8e04-400a-11e7-8990-c42258269299.png)

Ramme 3.1.0.80
macOS 10.12.5

**Comment by ludviglindblom** [comment] 2017-05-24 12:07
Same for me.
Ramme 3.1.0.80
macOS 10.12.4

![screen shot 2017-05-24 at 14 06 17](https://cloud.githubusercontent.com/assets/445328/26402368/5b493504-408a-11e7-97b0-8dd9c0e5b72c.png)

**Comment by bil-elmoussaoui** [comment] 2017-05-24 19:14
I can't confirm this bug...Can anyone help me to reproduce it?

**Comment by acdcpow** [comment] 2017-05-24 19:56
same here!
ramme 3.1.0
windows 10 1703
![capture d ecran 2](https://cloud.githubusercontent.com/assets/21224020/26422822/3f64d792-40c3-11e7-9730-2e1b67f09b19.png)

**Comment by anatolinicolae** [comment] 2017-05-24 20:06
I'm pretty sure this happens when you try to post a new picture then get back to home. Try this!

**Comment by bil-elmoussaoui** [comment] 2017-05-24 20:25
Nop couldn't reproduce it :( I think it's due to the minWidth of the window! I will set it few pixels more and push it and we will see if this is still happening.

**Comment by yimankaing** [comment] 2017-05-25 12:36
This might be our screen resolution. I have only 1366*768.

**Comment by bil-elmoussaoui** [comment] 2017-05-25 12:37
@yimankaing I've modified the minWidth to see if things will change; i will try later using my laptop!

**Comment by yimankaing** [comment] 2017-05-25 12:38
Thanks so much! I love this app!

**Comment by bil-elmoussaoui** [comment] 2017-05-25 17:44
@yimankaing Tried this on my laptop and seems to work fine. I will try to push a new release soon and see if things are still the same

**Comment by d0od88** [comment] 2017-05-25 21:08
Issue persists in latest version running on Ubuntu 17.04. I tried by the installer and the AppImage.

![screenshot from 2017-05-25 22-04-11](https://cloud.githubusercontent.com/assets/869982/26470705/9296c71c-4196-11e7-983f-774994027a77.png)

**Comment by bil-elmoussaoui** [comment] 2017-05-25 21:11
@d0od88 I can fix it if i can reproduce it, but i tried on both of my screens and it works without any issue. Maybe because i was running the dev version. I will try the AppImage right now!

**Comment by acdcpow** [comment] 2017-05-26 04:11
[Ramme 3.2.0] Same thing for windows 10.
![capture d ecran 3](https://cloud.githubusercontent.com/assets/21224020/26480426/a70b0c68-41d1-11e7-93e1-92026d87d253.png)

**Comment by bil-elmoussaoui** [comment] 2017-05-26 21:37
@d0od88 @anatolinicolae Just pushed a fix on master. As i can't reproduce the issue, would like to try a package if i build that for you? if so, can you tell me which distro you're using

**Comment by anatolinicolae** [comment] 2017-05-26 22:10
Yeah, I had the same issue and I guess I figured it out. Let us now if v3.2.1 (coming in few hours) fixed it or not!

**Comment by acdcpow** [comment] 2017-05-27 12:56
I didn't know where to put this, 
I got an error with 3.2.1  [WINDOWS10]
**it says "** ERROR : A JavaScript error occured in the main process
  uncaucht exception:
  typeError: Error processing argument at index 0, conversion failure from
    at Object.exports.createtray
    at App. <anonymous>
    at emitTwo (events.js:111:20)
    at App.emit (events.js.191:7) **"**

**Comment by bil-elmoussaoui** [comment] 2017-05-27 12:57
@acdcpow How did you get this error? when you start the application?

**Comment by anatolinicolae** [comment] 2017-05-27 12:58
@acdcpow It looks like a tray issue so to be sure please open a new issue regarding this.

**Comment by acdcpow** [comment] 2017-05-27 13:03
@anatolinicolae Done,
@bil-elmoussaoui Yes!

**Comment by d0od88** [comment] 2017-05-28 17:32
F-F-F-fixed! 

![screenshot from 2017-05-28 18-20-16](https://cloud.githubusercontent.com/assets/869982/26530805/0b31b698-43d4-11e7-9f91-d228ddd27d3b.png)

**Closed** 2017-05-28 17:33 UTC
Labels: layout issue, linux, mac
