### ISSUE TITLE
The process continues to run after close the program

### ISSUE THREAD

**Issue by antonyrod** [terkelg/ramme#19] opened 2016-08-27 10:29 UTC
Steps:
1. Close the program being authorized.

Actual result:
- In the Windows Task Manager still 3 of the same name of the process are running: Ramme.exe

Expected Result:
- After closing the program completed all the processes associated with it.
            -

            Ramme 2.0.0
            Electron 1.3.4
            win32 ia32 10.0.10240
ОС Microsoft Windows 10 Enterprise 64bit

**Comment by terkelg** [comment] 2016-08-27 11:26
I don't have access to a windows machine. It it possible that you can help out with this?

**Comment by BoredMind** [comment] 2016-08-27 23:19
This is happening for me as well.  Whatever help you need let me know and I'll help out.

**Comment by vintagesucks** [comment] 2016-08-28 03:59
Happening for me as well. I think the expected result after closing the window would be Ramme being minimized to the system tray, but instead it's just disappearing in the background as described by @antonyrod. The real issue here is the missing tray icon, I guess.

```
Ramme 2.0.0, Windows 10 Pro 10.0.10240.0
```

**Comment by terkelg** [comment] 2016-08-28 17:07
@BoredMind @antonyrod can you test the latest dev branch?
https://github.com/terkelg/ramme/tree/dev

I think I've found the bug 🎉

**Comment by BoredMind** [comment] 2016-08-28 18:25
@terkelg Do you have a Windows build from the dev branch?  I don't have a system setup with Electron to build it right now.

**Comment by vintagesucks** [comment] 2016-08-28 19:04
@terkelg The issue @antonyrod described is still present in the latest `dev` branch, but as I [said](#issuecomment-242954824), I think running in the background after closing the window this is not a bug but a **feature**. From the Ramme README:

> ### Background behavior  
When closing the window, the app will continue running in the background, in the dock on macOS and the tray on Linux/Windows. Right-click the dock/tray icon and choose `Quit` to completely quit the app.

The only thing that is missing here is a way to quit Ramme (-> the described tray icon/menu), but PR #21 should solve this when refactored into a seperate file.

**Comment by terkelg** [comment] 2016-08-28 19:11
You're right‚ @vintagesucks. I agree. Let's add that tray menu!

**Comment by vintagesucks** [comment] 2016-08-28 21:16
@terkelg Refactored into tray.js, see PR #23. Please note that I could test/optimize the tray icon toggle functionality for Windows only, so feel free to change the behavior depending on the platform. The Windows tray works quite different compared to the OS X toolbar, I'd suspect.

**Comment by terkelg** [comment] 2016-08-29 09:39
Should be fixed with commit 19bd1f7. Please test the latest master branch to confirm 👍

**Comment by vintagesucks** [comment] 2016-08-29 13:12
@terkelg This is fixed in the latest master branch. :+1:

**Closed** 2016-08-29 13:14 UTC
Labels: bug
