### ISSUE TITLE
Crash: Cannot read property 'name' of undefined at launch

### ISSUE THREAD

**Issue by octacian** [terkelg/ramme#184] opened 2017-08-17 02:57 UTC
* Ramme Version: 3.2.3
* Operating System: Ubuntu 17.04
* Installed via `dpkg`

Ramme does not launch and instead throws the following error:
```
TypeError: Cannot read property 'name' of undefined
    at getConf (/opt/Ramme/resources/app.asar/node_modules/first-run/index.js:13:73)
    at firstRun (/opt/Ramme/resources/app.asar/node_modules/first-run/index.js:25:13)
    at Object.exports.init (/opt/Ramme/resources/app.asar/dist/main/analytics.js:1:388)
    at App.<anonymous> (/opt/Ramme/resources/app.asar/dist/main/index.js:9:36)
    at emitTwo (events.js:111:20)
    at App.emit (events.js:194:7)
```

**Comment by bil-elmoussaoui** [comment] 2017-08-17 10:23
Duplicate of https://github.com/terkelg/ramme/issues/151

**Closed by bil-elmoussaoui** 2017-08-17 10:23 UTC
