### ISSUE TITLE
Linux issue with resizing and properly centering the feed/etc.

### ISSUE THREAD

**Issue by Cursewords** [terkelg/ramme#144] opened 2017-06-01 21:48 UTC
On Linux (Xubuntu fresh install) the app doesn't properly display. Feed window and pictures are pushed into the right which results in truncating about 20% of the window elements.

**Comment by pedrofleck** [comment] 2017-06-03 04:31
I confirm to have this issue too, and the upper bar also cuts a little the feed.

**Comment by bil-elmoussaoui** [comment] 2017-06-03 09:35
Duplicate of #125

**Closed by bil-elmoussaoui** 2017-06-03 09:35 UTC
