### ISSUE TITLE
Unable to choose location 

### ISSUE THREAD

**Issue by alaminos** [terkelg/ramme#173] opened 2017-07-30 17:00 UTC
In the last stage of posting an image, there is the caption box and the "add location" option. Clicking on add location pops this message:

_Enable Location Services
Turn Location Services on to add a location to your post._

Notice that "Enable Location Services" is not clickable and there is no further explanation on how to proceed.

Samsung Laptop 
Windows 8.1

**Comment by bil-elmoussaoui** [comment] 2017-08-17 10:29
@anatolinicolae @terkelg There must be something that should be enabled using Electron?

**Comment by terkelg** [comment] 2017-08-17 17:54
That's strange. Maybe @anatolinicolae can test on Windows?

**Comment by CodeBrauer** [comment] 2017-08-21 16:09
Same on macOS?

**Comment by octacian** [comment] 2017-08-29 03:04
The issue is present on Linux as well. Quite honestly, I don't think that this can be easily fixed with the current implementation of Ramme. I don't think it's possible to deal with this through Electron alone, most computers do not have a GPS chip in the first place. The only solution as is would be to write a custom location selection widget and somehow format the data so that Instagram will accept it.

The only other way to deal with this is alongside a rewrite to fetch content from the official Instagram APIs.

**Comment by octacian** [comment] 2017-10-03 01:33
Until the underlying issue is solved, I've hidden the `Add Location` button from the New Post window.

747f5a991aedd352d371471230c03cf42e28352a

**Closed** 2019-11-02 23:03 UTC
Labels: bug
