### ISSUE TITLE
Incorrect scrolling Instagram feed

### ISSUE THREAD

**Issue by antonyrod** [terkelg/ramme#18] opened 2016-08-27 10:17 UTC
Steps:
1. Begin to scroll feed or the user profile.
2. Reach the bottom.

Actual result:
- Scrolling stops.
- Resize window.
- There are new posts, you can scroll further.
  http://i.imgur.com/Rkia1kv.gifv

Expected Result:
- Correct scrolling feed, without having to change the window size.
  
  ```
      -
  
      Ramme 2.0.0
      Electron 1.3.4
      win32 ia32 10.0.10240
  ```

**Comment by terkelg** [comment] 2016-08-27 11:28
That's strange! I'll try to reproduce this and find a solution.

**Comment by willrun4fun** [comment] 2016-08-28 09:35
I am having the same problem.  Ubuntu 16.04 Unity.

**Comment by terkelg** [comment] 2016-08-28 16:55
Thanks @antonyrod and @willrun4fun. Is it possible you're up for this bug?
I don't have the issue on macOS, and it could be super cool if you guys could help with this one.

**Comment by mckennajones** [comment] 2016-08-28 17:46
Experiencing the same issue on Arch Linux with Gnome Desktop. I will look into it when I have some time

**Comment by terkelg** [comment] 2016-08-28 17:48
That's so cool, thanks man!
I love the open source community.

**Comment by terkelg** [comment] 2016-09-05 14:56
@mckennajones, @willrun4fun and @antonyrod - Can you check the latest master release and confirm if this is fixed by #42?

**Comment by antonyrod** [comment] 2016-09-05 16:20
Issue is not fixed yet.
Plus a few seconds after the program start getting these errors:
http://i.imgur.com/ee9XW3H.png
http://i.imgur.com/Sx6xaCM.png

**Comment by terkelg** [comment] 2016-09-05 17:01
Alright, I need to setup a virtual machine with Windows and look at this. Thanks for reporting.
I think the errors are related to the update check

**Comment by terkelg** [comment] 2016-09-05 22:10
@antonyrod is the last errors new in this release? I suspect it's due to the "update" functionality added in the latest version

**Comment by mckennajones** [comment] 2016-09-06 05:00
@terkelg My apologies, I haven't been able to find much free time lately to investigate it more. However I just tested the latest master release and the issue is still present for me on the Linux version :( I tested on Arch Linux.

**Comment by antonyrod** [comment] 2016-09-06 07:37
@terkelg yes the last errors are reproduced in the new release v2.2.0

**Comment by terkelg** [comment] 2016-09-06 21:09
Thanks for the feedback! I'll look at it

**Comment by terkelg** [comment] 2016-09-10 15:33
I just installed Windows on a VM and I don't get the error alert

**Comment by antonyrod** [comment] 2016-09-19 16:45
Topiс issue is repeated in the user profile:
http://i.imgur.com/zHR2lJv.gifv

**Comment by terkelg** [comment] 2016-09-19 16:48
Thanks for reporting @antonyrod. Do you still get the update error?
Can you look at the scrolling issue @anatolinicolae?

**Comment by anatolinicolae** [comment] 2016-09-19 17:10
I think I experienced the same issue in a past version but will check it again and push a fix. 😉

**Comment by terkelg** [comment] 2016-09-19 17:11
You're the man! Thanks a lot

**Comment by terkelg** [comment] 2017-05-09 11:27
What's the status on this @anatolinicolae?

**Comment by octacian** [comment] 2017-08-29 02:44
I don't think this is an issue anymore, pretty sure I fixed something related to this in my UI improvements PR not long ago. The error alert is a separate problem, so if anyone can confirm that it still occurs, a new issue should be opened for this. Finally, unless the scrolling issue is entirely platform dependent, I can confirm it does not occur on Ubuntu 17.04.

**Closed** 2019-11-02 23:03 UTC
Labels: bug, help wanted
