### ISSUE TITLE
Feat: Appimage distribution

### ISSUE THREAD

**Issue by armand1m** [terkelg/ramme#80] opened 2017-01-02 19:03 UTC
I was thinking and It would be nice to have `.appimage` build files available for simple distribution of the application in the Releases tab.

**Comment by anatolinicolae** [comment] 2017-01-02 19:16
Duplicate of #68. It's already in v3 branch ;)

**Closed by anatolinicolae** 2017-01-02 19:16 UTC
Labels: duplicate

**Comment by probonopd** [comment] 2019-06-03 17:58
Please reopen. I don't see an AppImage on https://github.com/terkelg/ramme/releases.
