### ISSUE TITLE
Layout setting not responsive and the top header blocks the content (Linux Mint 18 )

### ISSUE THREAD

**Issue by blackinitial** [terkelg/ramme#186] opened 2017-08-18 00:57 UTC
<a href="http://i.imgur.com/TTyZJGL.png">
  <img src="http://imgur.com/TTyZJGLl.png" />
</a>
<br>
<a href="http://i.imgur.com/dPHmVtd.png">
  <img src="http://imgur.com/dPHmVtdl.png" />
</a>
<br><br>
The layout setting not responsive in my linux mint 18 (sonya) and the top header blocks the content when the content is top.

**Comment by bil-elmoussaoui** [comment] 2017-08-18 19:45
Duplicate of #179

**Closed by bil-elmoussaoui** 2017-08-18 19:45 UTC
