### ISSUE TITLE
"5xx Server Error" on profile link click

### ISSUE THREAD

**Issue by seven11nash** [terkelg/ramme#17] opened 2016-08-26 23:34 UTC
I noticed that a "5xx Server Error" occurs when trying to open a link found on the profile of any user. The link that opens in the browser is also a different one than the one that comes when clicking the link on profiles on [Instagrams webapp](https://instagram.com/).

![screen shot 2016-08-27 at 01 26 11](https://cloud.githubusercontent.com/assets/5675238/18023145/b3be9004-6bf5-11e6-889f-9b0e6ea6209e.png)

The link that comes from ramme:
http://l.instagram.com/?e=ATNXK7V8hWA5Ro-TL_K0ZVA9750kBRqplk1T0SAXA1jgdfZrMbK54isjWj4gLA&u=http%3A%2F%2Fmomueller.com%2F

The link that comes from the instagram page:
http://l.instagram.com/?e=ATMzoiGO2WEe5uU_BtiNkNkZZ-j1WIo24youfOL2WKmDY8i0fip8Hf0wGKkIGA&u=http%3A%2F%2Fmomueller.com%2F

Im not sure if its the apps fault that the link is different or if thats some other problem, but it is weird that you get a "5xx Server Error".

Hope you can find the issue! Love what you are doing by the way, is there any way I could follow what you make in the future? Maybe we could even try making something together ;)

**Comment by terkelg** [comment] 2016-08-28 16:52
Thanks for the kind words! I'm always up for building great stuff.

I can't reproduce this myself. Do you still have this issue? I think this is a bug from Instagram, and hard for me to fix. Please let me know if you can reproduce it.

**Comment by seven11nash** [comment] 2016-08-28 16:55
Nope, I can't, seems to be gone... I'm Marc btw, the guy working on the website 😅 , just working on it right now actually.

**Comment by terkelg** [comment] 2016-08-28 16:58
Nice Marc! I'll close the issue.
I found a way for you to contribute to the gh-branche: http://stackoverflow.com/questions/9135913/merge-pull-request-to-a-different-branch-than-default-in-github

**Closed by terkelg** 2016-08-28 16:58 UTC
