### ISSUE TITLE
UI Alignment problem?

### ISSUE THREAD

**Issue by harchus** [terkelg/ramme#148] opened 2017-06-07 04:55 UTC
Using the latest version of the app on Windows 10, the timeline and the profile page get cut off, you can't se the images properly since photos are not centered, as you can see on my attachment the home icon as my username and profile picture are cut off. :(

Thank you so much for creating such a wonderful tool to navigate our Instagram accounts. <3

![ramme](https://user-images.githubusercontent.com/12431193/26862719-7d396fb2-4b1b-11e7-88f4-fb4d0a31fece.PNG)

**Comment by adriorosa** [comment] 2017-06-07 11:45
Same problem in Mac OS version
![captura de pantalla 2017-06-07 a las 13 45 06](https://user-images.githubusercontent.com/26595835/26876669-9a074a4e-4b87-11e7-885e-4595e7212266.png)

**Comment by bil-elmoussaoui** [comment] 2017-06-07 11:48
Duplicate of #125

**Closed by bil-elmoussaoui** 2017-06-07 11:48 UTC
