### ISSUE TITLE
The menu seems in the wrong position

### ISSUE THREAD

**Issue by SidKwok** [terkelg/ramme#207] opened 2017-09-22 06:46 UTC
![2017-09-22 14 45 51](https://user-images.githubusercontent.com/13268747/30732352-cb3ef842-9f37-11e7-844b-524825b3c817.png)

os: macOS 10.12.6
version: 3.2.3

**Comment by BeardDesign1** [comment] 2017-09-22 09:06
same problem here:
![](http://i.dont.have.a.beard-design.com/VIuCsLZX.png)
os: Windows 10 15063.608
version: 3.2.3

**Comment by octacian** [comment] 2017-09-22 14:31
This has already been fixed as of the latest master, just waiting for a new release. If I remember correctly though, a new release hasn't been made as there is some bug remaining that needs to be fixed first :thinking:

**Comment by terkelg** [comment] 2017-09-23 04:48
I can't release a new update since the build is broken on mac. Recent commits broke the build. Don't have the time to look into it though. I'm pretty sure it's after you did some changes @octacian, maybe you can have a look into it?

**Comment by octacian** [comment] 2017-09-24 14:45
@terkelg Will do my best, but I'm not quite sure as to what the cause is yet as I don't experience the issue on Linux.

**Comment by Vetronus** [comment] 2017-09-28 03:54
It's even worse in my case
![screen shot 2017-09-28 at 9 23 03 am](https://user-images.githubusercontent.com/24976752/30948610-be3a4aba-a42e-11e7-8222-e27c7964221a.png)

**Comment by NabiKAZ** [comment] 2017-09-29 20:25
I have same this problem in Windows 10 64-bit

![image](https://user-images.githubusercontent.com/246721/31034584-90998212-a571-11e7-960e-68bb66c73e49.png)

**Comment by therishabhpandey** [comment] 2017-10-08 10:58
Is it being worked on? If not, I'll try it.

**Comment by octacian** [comment] 2017-10-08 16:22
This has been temporarily fixed until the rewrite is complete. The fix should be in the next release, which is being delayed for some reason :thinking:

**Comment by fahmifan** [comment] 2017-11-19 08:59
Hope the fix will release soon

**Comment by MrScrog** [comment] 2018-01-24 18:25
same problem here
![image](https://user-images.githubusercontent.com/31424611/35349822-51064afa-013c-11e8-94bb-84b1b8ab0afb.png)

**Closed** 2019-11-02 23:03 UTC
Labels: bug, hacktoberfest
