### ISSUE TITLE
Check a screenshot 

### ISSUE THREAD

**Issue by ed4jonson** [terkelg/ramme#135] opened 2017-05-30 03:45 UTC
https://www.dropbox.com/s/1kptfi4y7igh9g7/Screenshot%20from%202017-05-30%2006-43-30.png?dl=0
            -

            Ramme 3.2.2
            Electron 1.7.2
            linux x64 4.10.0-21-generic

**Comment by alexsalex** [comment] 2017-05-30 17:36
The same thing....

MacOS 10.12.5

**Comment by bil-elmoussaoui** [comment] 2017-05-30 21:20
Duplicate of #125

**Closed by bil-elmoussaoui** 2017-05-30 21:20 UTC
